# A workflow for building Java Maven project
name: Build Java Maven project
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup JDK 11 (Liberica)
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'liberica'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Make GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/simple-xml-validator-*.jar"
